# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: f8d4db9
_src_path: gh:danjac/django-studio
author: Your Name
author_email: you@example.com
description: A Django project
domain: example.com
license: MIT
package_name: photoblog
project_name: Photo Blog
project_slug: photoblog
