# Generated by Django 6.0.3 on 2026-03-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="photo",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
