# Generated by Django 6.0.3 on 2026-03-22 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0003_photo_search_vector"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ("-created",)},
        ),
    ]
