# Generated by Django 6.0.3 on 2026-03-28 16:24

import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0004_alter_photo_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="description",
            field=models.TextField(blank=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                upload_to="photos/", verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="title",
            field=models.CharField(max_length=250, verbose_name="title"),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        blank=True, max_length=60, unique=True, verbose_name="tag"
                    ),
                ),
                (
                    "photos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="tags",
                        to="photos.photo",
                        verbose_name="photos",
                    ),
                ),
            ],
            options={
                "verbose_name": "tag",
                "verbose_name_plural": "tags",
            },
        ),
    ]
