# Generated by Django 6.0.3 on 2026-03-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0005_alter_photo_description_alter_photo_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.SlugField(
                blank=True, max_length=60, unique=True, verbose_name="tag"
            ),
        ),
    ]
