# Generated by Django 6.0.3 on 2026-03-29 12:00

import sorl.thumbnail.fields
from django.db import migrations

import photoblog.photos.models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0006_tag_tag_slugfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=sorl.thumbnail.fields.ImageField(
                upload_to=photoblog.photos.models.upload_handler, verbose_name="image"
            ),
        ),
    ]
