# Generated by Django 6.0.3 on 2026-03-22 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_alter_comment_options_alter_comment_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("-created",)},
        ),
    ]
